# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  URI_MONGO: 'mongodb://user:password@test:27017'
  DB_HOST: 'localhost'
  DB_USER: 'user'
  DB_PASS: 'password'
  DB_PORT: 3306
  DB_NAME: 'test'
  JWT_KEY: 'test'

jobs:
  node-v14-test:
    runs-on: ubuntu-latest
    container: node:14-alpine

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: 'user'
          MONGO_INITDB_ROOT_PASSWORD: 'password'
          MONGO_INITDB_DATABASE: 'test'
        ports: 27017
        options: --health-cmd="mongo" --health-interval=10s --health-timeout=5s --health-retries=5
      mysql:
        image: mysql
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports: 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install git
      run: apk add --no-cache git
    - name: Configure HTTP clone  
      run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - name: Install dependencies
      run: npm ci
    - name: Run test
      run: npm test
    - name: Run ESLint
      run: npm run eslint

  node-v16-test:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install dependencies
      run: npm ci
    - name: Run test
      run: npm test
    - name: Run ESLint
      run: npm run eslint
