# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

env:
  URI_MONGO: ${{ secrets.TEST_URI_MONGO }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

jobs:
  node-v14-test:
    runs-on: ubuntu-latest
    container: node:14-alpine

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install & Test
      run: npm ci
      run: npm test

  node-v16-test:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install & Test
      run: npm ci
      run: npm test
