const mongoose = require('mongoose');
const deviceSchema = new mongoose.Schema({ // Defines our collections - ONE COLLECTION PER DEVICE
  info : {
    location : String,
    name : String,
    owner : String,
  },
  data : { // Sent in packets every hour (?), written locally, processed and added to DB by server
    airtemperature : [
      { value : Number, timestamp : Date } // NOTE: Timestamp parsed to Date object by server
    ],
    airhumidity : [
      { value : Number, timestamp : Date }
    ],
    // TODO: Other datasets?
  },
  state : {
    online : Boolean, //Set by server
    lastonline : Date, // NOTE: Set ONCE by server on device DISCONNECT (i.e. not updated while continuously online, WILL BE OLD DATA)
    diagnostics : { // Updated by device more frequently
      lastupdate: Date, // NOTE: Generated by server on recieve
      power : Number,
      storage : Number,
      // TODO: Other diagnostics?
    },
    config : { // Sent to device by MQTT broker more frequently
      enabled : Boolean, 
      packetfrequency : Number, // How often are data packets sent (seconds)?
      // TODO: Other config items?
    }
  }
});

module.exports = mongoose.model('DeviceData', deviceSchema);